In [212]:
#coding: utf-8
import cython
import numpy as np
import pandas as pd
import scipy
import pymysql
from numba import jit
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import wrapt
import time
import os
from multiprocessing import Pool
%matplotlib inline
%load_ext Cython

The Cython extension is already loaded. To reload it, use:
  %reload_ext Cython

In [214]:
def RBreaker(yes_high,yes_low,yes_close):
    s_setup=yes_high+0.35*(yes_close-yes_low)
    b_setup=yes_low-0.35*(yes_high-yes_close)
    senter=1.07/2*(yes_high+yes_low)-0.07*yes_low
    benter=1.07/2*(yes_high+yes_low)-0.07*yes_high
    b_break=s_setup+0.25*(s_setup-b_setup)
    s_break=b_setup-0.25*(s_setup-b_setup)
    return [s_setup,b_setup,senter,benter,b_break,s_break]

In [232]:
def rbreaker(category):
    intra_df=pd.read_csv('%s_intraday.csv'%category.lower(),encoding='gbk')
    intra_df['update_date']=pd.to_datetime(intra_df['update_date'])

    interday_df=pd.read_csv('%s_interday.csv'%category.lower(),encoding='gbk',header=3)
    interday_df['Date']=pd.to_datetime(interday_df['Date'])
    interday_df=interday_df.rename(columns={'Date':'update_date'})
    interday_df['open']=interday_df['open'].astype(float)
    interday_df['high']=interday_df['high'].astype(float)
    interday_df['low']=interday_df['low'].astype(float)
    interday_df['close']=interday_df['close'].astype(float)

    interday_df['high_yes']=interday_df['high'].shift(1)
    interday_df['low_yes']=interday_df['low'].shift(1)
    interday_df['close_yes']=interday_df['close'].shift(1)

    rb=map(RBreaker,interday_df['high_yes'],interday_df['low_yes'],interday_df['close_yes'])

    rb=pd.DataFrame(rb,columns=['s_setup','b_setup','senter','benter','b_break','s_break'])
    rb['update_date']=interday_df['update_date']

    rb=rb.rename(columns={'update_date':'date'})
    rb['date']=pd.to_datetime(rb['date'])

    intra_df['date']=intra_df['update_date'].apply(lambda x:x.date())
    intra_df['date']=pd.to_datetime(intra_df['date'])

    intra_df=pd.merge(intra_df,rb,on=['date'],how='inner')

    intra_df=intra_df.dropna(axis=0)

    intra_df=intra_df.drop(['volume'],axis=1)

    intra_df_cop=pd.DataFrame()
    for i,j in intra_df.groupby(['date']):
        j=j.sort('update_date')
        stop_loss_point=list(j['open'])[0]
        j['high_max']=j['high'].cummax()
        j['low_min']=j['low'].cummin()


        col_list=list(j.columns)
        open_lab=col_list.index('open')
        high_lab=col_list.index('high')
        low_lab=col_list.index('low')
        close_lab=col_list.index('close')
        s_setup_lab=col_list.index('s_setup')
        b_setup_lab=col_list.index('b_setup')
        senter_lab=col_list.index('senter')
        benter_lab=col_list.index('benter')
        b_breaker_lab=col_list.index('b_break')
        s_breaker_lab=col_list.index('s_break')
        high_max_lab=col_list.index('high_max')
        low_min_lab=col_list.index('low_min')

        p_mat=j.as_matrix()
        sig=np.zeros(p_mat.shape[0],dtype=np.float)
        for k in range(1,p_mat.shape[0]-1):
            #突破做多
            if p_mat[k,high_lab]>p_mat[k,b_break_lab]:
                sig[k+1]=1
            elif p_mat[k,low_lab]>stop_loss_point and sig[k]==1:
                sig[k+1]=1
            #突破做空
            elif p_mat[k,low_lab]<p_mat[k,s_break_lab]:
                sig[k+1]=-1
            elif p_mat[k,high_lab]<stop_loss_point and sig[k]==-1:
                sig[k+1]=-1
            #反转做多做空
            else:
                if p_mat[k,high_max_lab]<p_mat[k,b_breaker_lab] and p_mat[k,high_max_lab]>p_mat[k,s_setup_lab] and p_mat[k,low_lab]<p_mat[k,senter_lab]:
                    sig[k+1]=-1
                elif p_mat[k,low_min_lab]>p_mat[k,s_breaker_lab] and p_mat[k,low_min_lab]<p_mat[k,b_setup_lab] and p_mat[k,high_lab]>p_mat[k,benter_lab]:
                    sig[k+1]=1
                else:
                    sig[k+1]=0



        j['sig']=sig
        intra_df_cop=intra_df_cop.append(j)

    intra_df_cop['return']=intra_df_cop['pctchange']*intra_df_cop['sig']

    intra_df_cop['cum']=intra_df_cop['return'].cumsum()
    return intra_df_cop

In [234]:
intra_df_cop_al=rbreaker('al')
intra_df_cop_cu=rbreaker('cu')
intra_df_cop_zn=rbreaker('zn')

2016-03-10 00:00:00
2016-03-11 00:00:00
2016-03-14 00:00:00
2016-03-15 00:00:00
2016-03-16 00:00:00
2016-03-17 00:00:00
2016-03-18 00:00:00
2016-03-21 00:00:00
2016-03-22 00:00:00
2016-03-23 00:00:00
2016-03-24 00:00:00
2016-03-25 00:00:00
2016-03-28 00:00:00
2016-03-29 00:00:00
2016-03-30 00:00:00
2016-03-31 00:00:00
2016-04-01 00:00:00
2016-04-05 00:00:00
2016-04-06 00:00:00
2016-04-07 00:00:00
2016-04-08 00:00:00
2016-04-11 00:00:00

/Users/liyuefan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:37: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

2016-04-12 00:00:00
2016-04-13 00:00:00
2016-04-14 00:00:00
2016-04-15 00:00:00
2016-04-18 00:00:00
2016-04-19 00:00:00
2016-04-20 00:00:00
2016-04-21 00:00:00
2016-04-22 00:00:00
2016-04-25 00:00:00
2016-04-26 00:00:00
2016-04-27 00:00:00
2016-04-28 00:00:00
2016-04-29 00:00:00
2016-05-03 00:00:00
2016-05-04 00:00:00
2016-05-05 00:00:00
2016-05-06 00:00:00
2016-05-09 00:00:00
2016-05-10 00:00:00
2016-05-11 00:00:00
2016-05-12 00:00:00
2016-05-13 00:00:00
2016-05-16 00:00:00
2016-05-17 00:00:00
2016-05-18 00:00:00
2016-05-19 00:00:00
2016-05-20 00:00:00
2016-05-23 00:00:00
2016-05-24 00:00:00
2016-05-25 00:00:00
2016-05-26 00:00:00
2016-05-27 00:00:00
2016-05-30 00:00:00
2016-05-31 00:00:00
2016-06-01 00:00:00
2016-06-02 00:00:00
2016-06-03 00:00:00
2016-06-06 00:00:00
2016-06-07 00:00:00
2016-06-08 00:00:00
2016-06-13 00:00:00
2016-06-14 00:00:00
2016-06-15 00:00:00
2016-06-16 00:00:00
2016-06-17 00:00:00
2016-06-20 00:00:00
2016-06-21 00:00:00
2016-06-22 00:00:00
2016-06-23 00:00:00
2016-06-24 00:00:00
2016-06-27 00:00:00
2016-06-28 00:00:00
2016-06-29 00:00:00
2016-06-30 00:00:00
2016-07-01 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-08-01 00:00:00
2016-08-02 00:00:00
2016-08-03 00:00:00
2016-08-04 00:00:00
2016-08-05 00:00:00
2016-08-08 00:00:00
2016-08-09 00:00:00
2016-08-10 00:00:00
2016-08-11 00:00:00
2016-08-12 00:00:00
2016-08-15 00:00:00
2016-08-16 00:00:00
2016-08-17 00:00:00
2016-08-18 00:00:00
2016-08-19 00:00:00
2016-08-22 00:00:00
2016-08-23 00:00:00
2016-08-24 00:00:00
2016-08-25 00:00:00
2016-08-26 00:00:00
2016-08-29 00:00:00
2016-08-30 00:00:00
2016-08-31 00:00:00
2016-09-01 00:00:00
2016-09-02 00:00:00
2016-09-05 00:00:00
2016-09-06 00:00:00
2016-09-07 00:00:00
2016-09-08 00:00:00
2016-09-09 00:00:00
2016-09-12 00:00:00
2016-09-13 00:00:00
2016-09-14 00:00:00
2016-09-19 00:00:00
2016-09-20 00:00:00
2016-09-21 00:00:00
2016-09-22 00:00:00
2016-09-23 00:00:00
2016-09-26 00:00:00
2016-09-27 00:00:00
2016-09-28 00:00:00
2016-09-29 00:00:00
2016-09-30 00:00:00
2016-10-10 00:00:00
2016-10-11 00:00:00
2016-10-12 00:00:00
2016-10-13 00:00:00
2016-10-14 00:00:00
2016-10-17 00:00:00
2016-10-18 00:00:00
2016-10-19 00:00:00
2016-10-20 00:00:00
2016-10-21 00:00:00
2016-10-24 00:00:00
2016-10-25 00:00:00
2016-10-26 00:00:00
2016-10-27 00:00:00
2016-10-28 00:00:00
2016-10-31 00:00:00
2016-11-01 00:00:00
2016-11-02 00:00:00
2016-11-03 00:00:00
2016-11-04 00:00:00
2016-11-07 00:00:00
2016-11-08 00:00:00
2016-11-09 00:00:00
2016-11-10 00:00:00
2016-11-11 00:00:00
2016-11-14 00:00:00
2016-11-15 00:00:00
2016-11-16 00:00:00
2016-11-17 00:00:00
2016-11-18 00:00:00
2016-11-21 00:00:00
2016-11-22 00:00:00
2016-11-23 00:00:00
2016-11-24 00:00:00
2016-11-25 00:00:00
2016-11-28 00:00:00
2016-11-29 00:00:00
2016-11-30 00:00:00
2016-12-01 00:00:00
2016-12-02 00:00:00
2016-12-05 00:00:00
2016-12-06 00:00:00
2016-12-07 00:00:00
2016-12-08 00:00:00
2016-12-09 00:00:00
2016-12-12 00:00:00
2016-12-13 00:00:00
2016-12-14 00:00:00
2016-12-15 00:00:00
2016-12-16 00:00:00
2016-12-19 00:00:00
2016-12-20 00:00:00
2016-12-21 00:00:00
2016-12-22 00:00:00
2016-12-23 00:00:00
2016-12-26 00:00:00
2016-12-27 00:00:00
2016-12-28 00:00:00
2016-12-29 00:00:00
2016-12-30 00:00:00
2017-01-03 00:00:00
2017-01-04 00:00:00
2017-01-05 00:00:00
2017-01-06 00:00:00
2017-01-09 00:00:00
2017-01-10 00:00:00
2017-01-11 00:00:00
2017-01-12 00:00:00
2017-01-13 00:00:00
2017-01-16 00:00:00
2017-01-17 00:00:00
2017-01-18 00:00:00
2017-01-19 00:00:00
2017-01-20 00:00:00
2017-01-23 00:00:00
2017-01-24 00:00:00
2017-01-25 00:00:00
2017-01-26 00:00:00
2017-02-03 00:00:00
2017-02-06 00:00:00
2017-02-07 00:00:00
2017-02-08 00:00:00
2017-02-09 00:00:00
2017-02-10 00:00:00
2017-02-13 00:00:00
2017-02-14 00:00:00
2017-02-15 00:00:00
2017-02-16 00:00:00
2017-02-17 00:00:00
2017-02-20 00:00:00
2017-02-21 00:00:00
2017-02-22 00:00:00
2017-02-23 00:00:00
2017-02-24 00:00:00
2017-02-27 00:00:00
2017-02-28 00:00:00
2017-03-01 00:00:00
2017-03-02 00:00:00
2017-03-03 00:00:00
2017-03-06 00:00:00
2017-03-07 00:00:00
2017-03-08 00:00:00
2017-03-09 00:00:00
2017-03-10 00:00:00
2016-03-10 00:00:00
2016-03-11 00:00:00
2016-03-14 00:00:00
2016-03-15 00:00:00
2016-03-16 00:00:00
2016-03-17 00:00:00
2016-03-18 00:00:00
2016-03-21 00:00:00
2016-03-22 00:00:00
2016-03-23 00:00:00
2016-03-24 00:00:00
2016-03-25 00:00:00
2016-03-28 00:00:00
2016-03-29 00:00:00
2016-03-30 00:00:00
2016-03-31 00:00:00
2016-04-01 00:00:00
2016-04-05 00:00:00
2016-04-06 00:00:00
2016-04-07 00:00:00
2016-04-08 00:00:00
2016-04-11 00:00:00
2016-04-12 00:00:00
2016-04-13 00:00:00
2016-04-14 00:00:00
2016-04-15 00:00:00
2016-04-18 00:00:00
2016-04-19 00:00:00
2016-04-20 00:00:00
2016-04-21 00:00:00
2016-04-22 00:00:00
2016-04-25 00:00:00
2016-04-26 00:00:00
2016-04-27 00:00:00
2016-04-28 00:00:00
2016-04-29 00:00:00
2016-05-03 00:00:00
2016-05-04 00:00:00
2016-05-05 00:00:00
2016-05-06 00:00:00
2016-05-09 00:00:00
2016-05-10 00:00:00
2016-05-11 00:00:00
2016-05-12 00:00:00
2016-05-13 00:00:00
2016-05-16 00:00:00
2016-05-17 00:00:00
2016-05-18 00:00:00
2016-05-19 00:00:00
2016-05-20 00:00:00
2016-05-23 00:00:00
2016-05-24 00:00:00
2016-05-25 00:00:00
2016-05-26 00:00:00
2016-05-27 00:00:00
2016-05-30 00:00:00
2016-05-31 00:00:00
2016-06-01 00:00:00
2016-06-02 00:00:00
2016-06-03 00:00:00
2016-06-06 00:00:00
2016-06-07 00:00:00
2016-06-08 00:00:00
2016-06-13 00:00:00
2016-06-14 00:00:00
2016-06-15 00:00:00
2016-06-16 00:00:00
2016-06-17 00:00:00
2016-06-20 00:00:00
2016-06-21 00:00:00
2016-06-22 00:00:00
2016-06-23 00:00:00
2016-06-24 00:00:00
2016-06-27 00:00:00
2016-06-28 00:00:00
2016-06-29 00:00:00
2016-06-30 00:00:00
2016-07-01 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-08-01 00:00:00
2016-08-02 00:00:00
2016-08-03 00:00:00
2016-08-04 00:00:00
2016-08-05 00:00:00
2016-08-08 00:00:00
2016-08-09 00:00:00
2016-08-10 00:00:00
2016-08-11 00:00:00
2016-08-12 00:00:00
2016-08-15 00:00:00
2016-08-16 00:00:00
2016-08-17 00:00:00
2016-08-18 00:00:00
2016-08-19 00:00:00
2016-08-22 00:00:00
2016-08-23 00:00:00
2016-08-24 00:00:00
2016-08-25 00:00:00
2016-08-26 00:00:00
2016-08-29 00:00:00
2016-08-30 00:00:00
2016-08-31 00:00:00
2016-09-01 00:00:00
2016-09-02 00:00:00
2016-09-05 00:00:00
2016-09-06 00:00:00
2016-09-07 00:00:00
2016-09-08 00:00:00
2016-09-09 00:00:00
2016-09-12 00:00:00
2016-09-13 00:00:00
2016-09-14 00:00:00
2016-09-19 00:00:00
2016-09-20 00:00:00
2016-09-21 00:00:00
2016-09-22 00:00:00
2016-09-23 00:00:00
2016-09-26 00:00:00
2016-09-27 00:00:00
2016-09-28 00:00:00
2016-09-29 00:00:00
2016-09-30 00:00:00
2016-10-10 00:00:00
2016-10-11 00:00:00
2016-10-12 00:00:00
2016-10-13 00:00:00
2016-10-14 00:00:00
2016-10-17 00:00:00
2016-10-18 00:00:00
2016-10-19 00:00:00
2016-10-20 00:00:00
2016-10-21 00:00:00
2016-10-24 00:00:00
2016-10-25 00:00:00
2016-10-26 00:00:00
2016-10-27 00:00:00
2016-10-28 00:00:00
2016-10-31 00:00:00
2016-11-01 00:00:00
2016-11-02 00:00:00
2016-11-03 00:00:00
2016-11-04 00:00:00
2016-11-07 00:00:00
2016-11-08 00:00:00
2016-11-09 00:00:00
2016-11-10 00:00:00
2016-11-11 00:00:00
2016-11-14 00:00:00
2016-11-15 00:00:00
2016-11-16 00:00:00
2016-11-17 00:00:00
2016-11-18 00:00:00
2016-11-21 00:00:00
2016-11-22 00:00:00
2016-11-23 00:00:00
2016-11-24 00:00:00
2016-11-25 00:00:00
2016-11-28 00:00:00
2016-11-29 00:00:00
2016-11-30 00:00:00
2016-12-01 00:00:00
2016-12-02 00:00:00
2016-12-05 00:00:00
2016-12-06 00:00:00
2016-12-07 00:00:00
2016-12-08 00:00:00
2016-12-09 00:00:00
2016-12-12 00:00:00
2016-12-13 00:00:00
2016-12-14 00:00:00
2016-12-15 00:00:00
2016-12-16 00:00:00
2016-12-19 00:00:00
2016-12-20 00:00:00
2016-12-21 00:00:00
2016-12-22 00:00:00
2016-12-23 00:00:00
2016-12-26 00:00:00
2016-12-27 00:00:00
2016-12-28 00:00:00
2016-12-29 00:00:00
2016-12-30 00:00:00
2017-01-03 00:00:00
2017-01-04 00:00:00
2017-01-05 00:00:00
2017-01-06 00:00:00
2017-01-09 00:00:00
2017-01-10 00:00:00
2017-01-11 00:00:00
2017-01-12 00:00:00
2017-01-13 00:00:00
2017-01-16 00:00:00
2017-01-17 00:00:00
2017-01-18 00:00:00
2017-01-19 00:00:00
2017-01-20 00:00:00
2017-01-23 00:00:00
2017-01-24 00:00:00
2017-01-25 00:00:00
2017-01-26 00:00:00
2017-02-03 00:00:00
2017-02-06 00:00:00
2017-02-07 00:00:00
2017-02-08 00:00:00
2017-02-09 00:00:00
2017-02-10 00:00:00
2017-02-13 00:00:00
2017-02-14 00:00:00
2017-02-15 00:00:00
2017-02-16 00:00:00
2017-02-17 00:00:00
2017-02-20 00:00:00
2017-02-21 00:00:00
2017-02-22 00:00:00
2017-02-23 00:00:00
2017-02-24 00:00:00
2017-02-27 00:00:00
2017-02-28 00:00:00
2017-03-01 00:00:00
2017-03-02 00:00:00
2017-03-03 00:00:00
2017-03-06 00:00:00
2017-03-07 00:00:00
2017-03-08 00:00:00
2017-03-09 00:00:00
2017-03-10 00:00:00
2016-03-10 00:00:00
2016-03-11 00:00:00
2016-03-14 00:00:00
2016-03-15 00:00:00
2016-03-16 00:00:00
2016-03-17 00:00:00
2016-03-18 00:00:00
2016-03-21 00:00:00
2016-03-22 00:00:00
2016-03-23 00:00:00
2016-03-24 00:00:00
2016-03-25 00:00:00
2016-03-28 00:00:00
2016-03-29 00:00:00
2016-03-30 00:00:00
2016-03-31 00:00:00
2016-04-01 00:00:00
2016-04-05 00:00:00
2016-04-06 00:00:00
2016-04-07 00:00:00
2016-04-08 00:00:00
2016-04-11 00:00:00
2016-04-12 00:00:00
2016-04-13 00:00:00
2016-04-14 00:00:00
2016-04-15 00:00:00
2016-04-18 00:00:00
2016-04-19 00:00:00
2016-04-20 00:00:00
2016-04-21 00:00:00
2016-04-22 00:00:00
2016-04-25 00:00:00
2016-04-26 00:00:00
2016-04-27 00:00:00
2016-04-28 00:00:00
2016-04-29 00:00:00
2016-05-03 00:00:00
2016-05-04 00:00:00
2016-05-05 00:00:00
2016-05-06 00:00:00
2016-05-09 00:00:00
2016-05-10 00:00:00
2016-05-11 00:00:00
2016-05-12 00:00:00
2016-05-13 00:00:00
2016-05-16 00:00:00
2016-05-17 00:00:00
2016-05-18 00:00:00
2016-05-19 00:00:00
2016-05-20 00:00:00
2016-05-23 00:00:00
2016-05-24 00:00:00
2016-05-25 00:00:00
2016-05-26 00:00:00
2016-05-27 00:00:00
2016-05-30 00:00:00
2016-05-31 00:00:00
2016-06-01 00:00:00
2016-06-02 00:00:00
2016-06-03 00:00:00
2016-06-06 00:00:00
2016-06-07 00:00:00
2016-06-08 00:00:00
2016-06-13 00:00:00
2016-06-14 00:00:00
2016-06-15 00:00:00
2016-06-16 00:00:00
2016-06-17 00:00:00
2016-06-20 00:00:00
2016-06-21 00:00:00
2016-06-22 00:00:00
2016-06-23 00:00:00
2016-06-24 00:00:00
2016-06-27 00:00:00
2016-06-28 00:00:00
2016-06-29 00:00:00
2016-06-30 00:00:00
2016-07-01 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-08-01 00:00:00
2016-08-02 00:00:00
2016-08-03 00:00:00
2016-08-04 00:00:00
2016-08-05 00:00:00
2016-08-08 00:00:00
2016-08-09 00:00:00
2016-08-10 00:00:00
2016-08-11 00:00:00
2016-08-12 00:00:00
2016-08-15 00:00:00
2016-08-16 00:00:00
2016-08-17 00:00:00
2016-08-18 00:00:00
2016-08-19 00:00:00
2016-08-22 00:00:00
2016-08-23 00:00:00
2016-08-24 00:00:00
2016-08-25 00:00:00
2016-08-26 00:00:00
2016-08-29 00:00:00
2016-08-30 00:00:00
2016-08-31 00:00:00
2016-09-01 00:00:00
2016-09-02 00:00:00
2016-09-05 00:00:00
2016-09-06 00:00:00
2016-09-07 00:00:00
2016-09-08 00:00:00
2016-09-09 00:00:00
2016-09-12 00:00:00
2016-09-13 00:00:00
2016-09-14 00:00:00
2016-09-19 00:00:00
2016-09-20 00:00:00
2016-09-21 00:00:00
2016-09-22 00:00:00
2016-09-23 00:00:00
2016-09-26 00:00:00
2016-09-27 00:00:00
2016-09-28 00:00:00
2016-09-29 00:00:00
2016-09-30 00:00:00
2016-10-10 00:00:00
2016-10-11 00:00:00
2016-10-12 00:00:00
2016-10-13 00:00:00
2016-10-14 00:00:00
2016-10-17 00:00:00
2016-10-18 00:00:00
2016-10-19 00:00:00
2016-10-20 00:00:00
2016-10-21 00:00:00
2016-10-24 00:00:00
2016-10-25 00:00:00
2016-10-26 00:00:00
2016-10-27 00:00:00
2016-10-28 00:00:00
2016-10-31 00:00:00
2016-11-01 00:00:00
2016-11-02 00:00:00
2016-11-03 00:00:00
2016-11-04 00:00:00
2016-11-07 00:00:00
2016-11-08 00:00:00
2016-11-09 00:00:00
2016-11-10 00:00:00
2016-11-11 00:00:00
2016-11-14 00:00:00
2016-11-15 00:00:00
2016-11-16 00:00:00
2016-11-17 00:00:00
2016-11-18 00:00:00
2016-11-21 00:00:00
2016-11-22 00:00:00
2016-11-23 00:00:00
2016-11-24 00:00:00
2016-11-25 00:00:00
2016-11-28 00:00:00
2016-11-29 00:00:00
2016-11-30 00:00:00
2016-12-01 00:00:00
2016-12-02 00:00:00
2016-12-05 00:00:00
2016-12-06 00:00:00
2016-12-07 00:00:00
2016-12-08 00:00:00
2016-12-09 00:00:00
2016-12-12 00:00:00
2016-12-13 00:00:00
2016-12-14 00:00:00
2016-12-15 00:00:00
2016-12-16 00:00:00
2016-12-19 00:00:00
2016-12-20 00:00:00
2016-12-21 00:00:00
2016-12-22 00:00:00
2016-12-23 00:00:00
2016-12-26 00:00:00
2016-12-27 00:00:00
2016-12-28 00:00:00
2016-12-29 00:00:00
2016-12-30 00:00:00
2017-01-03 00:00:00
2017-01-04 00:00:00
2017-01-05 00:00:00
2017-01-06 00:00:00
2017-01-09 00:00:00
2017-01-10 00:00:00
2017-01-11 00:00:00
2017-01-12 00:00:00
2017-01-13 00:00:00
2017-01-16 00:00:00
2017-01-17 00:00:00
2017-01-18 00:00:00
2017-01-19 00:00:00
2017-01-20 00:00:00
2017-01-23 00:00:00
2017-01-24 00:00:00

In [249]:
intra_df_cop_al_std=pd.DataFrame(intra_df_cop_al.groupby(['date']).pctchange.std())
intra_df_cop_al_std=intra_df_cop_al_std.rename(columns={'pctchange':'al'})

intra_df_cop_cu_std=pd.DataFrame(intra_df_cop_cu.groupby(['date']).pctchange.std())
intra_df_cop_cu_std=intra_df_cop_cu_std.rename(columns={'pctchange':'cu'})

intra_df_cop_zn_std=pd.DataFrame(intra_df_cop_zn.groupby(['date']).pctchange.std())
intra_df_cop_zn_std=intra_df_cop_zn_std.rename(columns={'pctchange':'zn'})

intra_df_cop_std=pd.concat([intra_df_cop_al_std,intra_df_cop_cu_std,intra_df_cop_zn_std],axis=1,join='inner')

In [258]:
intra_df_cop_std.reset_index(inplace=True)

In [264]:
intra_df_cop_std

          date        al        cu        zn
0   2016-03-10  0.000547  0.000577  0.000744
1   2016-03-11  0.000433  0.000561  0.000583
2   2016-03-14  0.000498  0.000659  0.000668
3   2016-03-15  0.000471  0.000523  0.000659
4   2016-03-16  0.000375  0.000473  0.000501
5   2016-03-17  0.000391  0.000537  0.000562
6   2016-03-18  0.000452  0.000696  0.000807
7   2016-03-21  0.000523  0.000495  0.000696
8   2016-03-22  0.000425  0.000409  0.000550
9   2016-03-23  0.000359  0.000521  0.000505
10  2016-03-24  0.000482  0.000430  0.000517
11  2016-03-25  0.000451  0.000257  0.000412
12  2016-03-28  0.000474  0.000395  0.000481
13  2016-03-29  0.000530  0.000478  0.000641
14  2016-03-30  0.000434  0.000559  0.000558
15  2016-03-31  0.000402  0.000516  0.000587
16  2016-04-01  0.000433  0.000402  0.000526
17  2016-04-05  0.000459  0.000452  0.000611
18  2016-04-06  0.000397  0.000375  0.000443
19  2016-04-07  0.000626  0.000591  0.000643
20  2016-04-08  0.000400  0.000413  0.000471
21  2016-04-11  0.000424  0.000500  0.000561
22  2016-04-12  0.000516  0.000592  0.000851
23  2016-04-13  0.000641  0.000719  0.000874
24  2016-04-14  0.000474  0.000485  0.000854
25  2016-04-15  0.000520  0.000454  0.000768
26  2016-04-18  0.000481  0.000582  0.001167
27  2016-04-19  0.000391  0.000576  0.000654
28  2016-04-20  0.000487  0.000625  0.000759
29  2016-04-21  0.001207  0.000993  0.001245
..         ...       ...       ...       ...
187 2016-12-13  0.000674  0.000788  0.000964
188 2016-12-14  0.000786  0.000734  0.000965
189 2016-12-15  0.000779  0.000855  0.001103
190 2016-12-16  0.000683  0.000655  0.000965
191 2016-12-19  0.000692  0.000780  0.001261
192 2016-12-20  0.000624  0.000569  0.001003
193 2016-12-21  0.000542  0.000501  0.000715
194 2016-12-22  0.000637  0.000627  0.000864
195 2016-12-23  0.000691  0.000675  0.000907
196 2016-12-26  0.000770  0.000945  0.001570
197 2016-12-27  0.000638  0.000680  0.000971
198 2016-12-28  0.000700  0.000738  0.001300
199 2016-12-29  0.000670  0.000673  0.000992
200 2016-12-30  0.000644  0.000471  0.000836
201 2017-01-03  0.000655  0.000734  0.000916
202 2017-01-04  0.000522  0.000632  0.000905
203 2017-01-05  0.000474  0.000559  0.000768
204 2017-01-06  0.000528  0.000520  0.000746
205 2017-01-09  0.000495  0.000479  0.000790
206 2017-01-10  0.000683  0.000637  0.000863
207 2017-01-11  0.000574  0.000587  0.000751
208 2017-01-12  0.000855  0.000655  0.000976
209 2017-01-13  0.000794  0.000593  0.000873
210 2017-01-16  0.000831  0.000609  0.000947
211 2017-01-17  0.001024  0.000682  0.001100
212 2017-01-18  0.000618  0.000641  0.000875
213 2017-01-19  0.000568  0.000523  0.000753
214 2017-01-20  0.000916  0.000560  0.000868
215 2017-01-23  0.000747  0.000585  0.000876
216 2017-01-24  0.000784  0.000631  0.000820

[217 rows x 4 columns]

In [260]:
std_mat=intra_df_cop_std.as_matrix()

In [261]:
std_mat

array([[Timestamp('2016-03-10 00:00:00'), 0.0005473161198033353,
        0.0005772985371059869, 0.0007440993521040376],
       [Timestamp('2016-03-11 00:00:00'), 0.00043303997984028505,
        0.0005614202240887504, 0.0005831887981385995],
       [Timestamp('2016-03-14 00:00:00'), 0.000497975558490722,
        0.0006593661814999276, 0.0006681647100507586],
       [Timestamp('2016-03-15 00:00:00'), 0.00047142671409379613,
        0.0005226098943993268, 0.0006590407320570825],
       [Timestamp('2016-03-16 00:00:00'), 0.000374937587928271,
        0.00047280730131407943, 0.0005007236851676903],
       [Timestamp('2016-03-17 00:00:00'), 0.00039117462369231323,
        0.0005367090572407081, 0.0005617028903736331],
       [Timestamp('2016-03-18 00:00:00'), 0.0004518381972872321,
        0.0006963867899698625, 0.0008067940567382374],
       [Timestamp('2016-03-21 00:00:00'), 0.0005225324292910865,
        0.0004947161418869881, 0.0006963119698011492],
       [Timestamp('2016-03-22 00:00:00'), 0.0004249957691776044,
        0.00040894203430372585, 0.0005501794775268294],
       [Timestamp('2016-03-23 00:00:00'), 0.0003594156955740761,
        0.0005213075658750839, 0.0005054805282201972],
       [Timestamp('2016-03-24 00:00:00'), 0.0004815991383892682,
        0.0004295755935019617, 0.0005169482274308773],
       [Timestamp('2016-03-25 00:00:00'), 0.00045117329915689015,
        0.00025707915168656897, 0.00041212152780587143],
       [Timestamp('2016-03-28 00:00:00'), 0.00047439021512895256,
        0.00039503920947863384, 0.0004808806023829852],
       [Timestamp('2016-03-29 00:00:00'), 0.0005296801137191301,
        0.0004784705799376778, 0.000641289501235343],
       [Timestamp('2016-03-30 00:00:00'), 0.0004344434696884004,
        0.0005593223005231151, 0.0005584182620564739],
       [Timestamp('2016-03-31 00:00:00'), 0.0004019044964357779,
        0.0005157724991895351, 0.0005866643937661241],
       [Timestamp('2016-04-01 00:00:00'), 0.00043317227099264445,
        0.0004015786321399185, 0.0005257790411074432],
       [Timestamp('2016-04-05 00:00:00'), 0.00045940488172791036,
        0.0004515099243781656, 0.0006107197799237934],
       [Timestamp('2016-04-06 00:00:00'), 0.0003973865691259119,
        0.00037545400163244684, 0.0004433273433953673],
       [Timestamp('2016-04-07 00:00:00'), 0.0006255912507240445,
        0.000590965117021077, 0.0006433482582493632],
       [Timestamp('2016-04-08 00:00:00'), 0.00039955281178760937,
        0.0004134368278668076, 0.00047101449118181236],
       [Timestamp('2016-04-11 00:00:00'), 0.00042388679255789274,
        0.0005000548454546267, 0.0005612765016544627],
       [Timestamp('2016-04-12 00:00:00'), 0.0005164637230147464,
        0.00059178020325601, 0.0008512742381983343],
       [Timestamp('2016-04-13 00:00:00'), 0.0006407176109061768,
        0.0007193634134365116, 0.0008737732265676147],
       [Timestamp('2016-04-14 00:00:00'), 0.00047445254387006535,
        0.00048514389941530433, 0.0008543474857834046],
       [Timestamp('2016-04-15 00:00:00'), 0.0005201082200136343,
        0.0004544032630608054, 0.0007683320564542599],
       [Timestamp('2016-04-18 00:00:00'), 0.00048143946238884814,
        0.0005822237633615858, 0.0011666224589694392],
       [Timestamp('2016-04-19 00:00:00'), 0.0003907520992503414,
        0.0005756969419009522, 0.0006542242045543526],
       [Timestamp('2016-04-20 00:00:00'), 0.0004867383376811193,
        0.0006250271294527546, 0.0007589053879268298],
       [Timestamp('2016-04-21 00:00:00'), 0.001207084152819408,
        0.0009928617523138582, 0.001244994728195596],
       [Timestamp('2016-04-22 00:00:00'), 0.0008938882067587114,
        0.0008287057726383652, 0.000949728110396835],
       [Timestamp('2016-04-25 00:00:00'), 0.0009620526077233834,
        0.0006345893439488606, 0.000705763125251198],
       [Timestamp('2016-04-26 00:00:00'), 0.0006211696788722147,
        0.0005384543695557882, 0.0007646682948370721],
       [Timestamp('2016-04-27 00:00:00'), 0.0009702511712255566,
        0.0005501795357798664, 0.0006663950488375357],
       [Timestamp('2016-04-28 00:00:00'), 0.0007909833445775396,
        0.0004966489275634068, 0.0006196100142687966],
       [Timestamp('2016-04-29 00:00:00'), 0.00048252960206664257,
        0.0004517687587502054, 0.0006907451428479419],
       [Timestamp('2016-05-03 00:00:00'), 0.0005803670876717286,
        0.0006872562272483713, 0.000781132713117946],
       [Timestamp('2016-05-04 00:00:00'), 0.0006268602709898093,
        0.0004935002607791888, 0.0005676102100594325],
       [Timestamp('2016-05-05 00:00:00'), 0.0006419777516620547,
        0.0005412618368847622, 0.0007161656926943224],
       [Timestamp('2016-05-06 00:00:00'), 0.0006764594327202347,
        0.0005461917762821138, 0.0006821772382793744],
       [Timestamp('2016-05-09 00:00:00'), 0.0010198631150540878,
        0.0007155427505558127, 0.0008365169993546066],
       [Timestamp('2016-05-10 00:00:00'), 0.0006881391993442138,
        0.0004976127410622954, 0.00061630696871941],
       [Timestamp('2016-05-11 00:00:00'), 0.0006170959431451631,
        0.0005177502323736659, 0.0008030013636344093],
       [Timestamp('2016-05-12 00:00:00'), 0.0008454159487202862,
        0.0007529173285081688, 0.0008745361259941196],
       [Timestamp('2016-05-13 00:00:00'), 0.0007876862011742707,
        0.0006972357258770691, 0.0008493348188726146],
       [Timestamp('2016-05-16 00:00:00'), 0.0006766306944603072,
        0.0006377612410199192, 0.0006500800909002968],
       [Timestamp('2016-05-17 00:00:00'), 0.0005801814533118924,
        0.0005522414820997893, 0.0005599423092059175],
       [Timestamp('2016-05-18 00:00:00'), 0.0006132806761498272,
        0.0006310362085445309, 0.000608269120260089],
       [Timestamp('2016-05-19 00:00:00'), 0.0005435269168864976,
        0.0006085403523460873, 0.0005954423472542387],
       [Timestamp('2016-05-20 00:00:00'), 0.0005852867075830552,
        0.000564754263224653, 0.0005646981536679273],
       [Timestamp('2016-05-23 00:00:00'), 0.0006615989938868117,
        0.000698178387120927, 0.0006727969973655523],
       [Timestamp('2016-05-24 00:00:00'), 0.0006335680904105578,
        0.0005571179965579902, 0.0008399593178025305],
       [Timestamp('2016-05-25 00:00:00'), 0.0006756615823818925,
        0.0005934402048741114, 0.0006614553057147252],
       [Timestamp('2016-05-26 00:00:00'), 0.0006712269662166466,
        0.00044797198828657917, 0.0005973268781583501],
       [Timestamp('2016-05-27 00:00:00'), 0.0006189026454616713,
        0.0004510247190536869, 0.0005576937081859757],
       [Timestamp('2016-05-30 00:00:00'), 0.0005590524856389336,
        0.0003729657647484906, 0.00044905556557693095],
       [Timestamp('2016-05-31 00:00:00'), 0.00048167658589521597,
        0.0004510363246734006, 0.0005209808603091519],
       [Timestamp('2016-06-01 00:00:00'), 0.000614174994570984,
        0.0004844024269848748, 0.0006955422008426094],
       [Timestamp('2016-06-02 00:00:00'), 0.0010014278232575492,
        0.00044187059125700264, 0.0008257776345521317],
       [Timestamp('2016-06-03 00:00:00'), 0.0006859949670237312,
        0.0006696899417690754, 0.0007504878949251774],
       [Timestamp('2016-06-06 00:00:00'), 0.0007158319353929587,
        0.0004846391587033239, 0.0006737271879589903],
       [Timestamp('2016-06-07 00:00:00'), 0.0005969700238637317,
        0.0007720232156184639, 0.0006163666701452555],
       [Timestamp('2016-06-08 00:00:00'), 0.0005197061860505813,
        0.0003201152582881312, 0.0005543472845597608],
       [Timestamp('2016-06-13 00:00:00'), 0.000774723595805131,
        0.0005443970093423168, 0.0007178870629034608],
       [Timestamp('2016-06-14 00:00:00'), 0.0005476886536031953,
        0.00041020650117583205, 0.0005598777608890841],
       [Timestamp('2016-06-15 00:00:00'), 0.0005230904521809196,
        0.000844050100080811, 0.0006111002207454409],
       [Timestamp('2016-06-16 00:00:00'), 0.0004388548607522175,
        0.00047423637540502933, 0.0005142469311363871],
       [Timestamp('2016-06-17 00:00:00'), 0.0004808823366036282,
        0.000418722723106826, 0.0006035353919989812],
       [Timestamp('2016-06-20 00:00:00'), 0.000611875456472781,
        0.00047127615853292015, 0.0005162164771696375],
       [Timestamp('2016-06-21 00:00:00'), 0.0004988155960931773,
        0.00040962814461748925, 0.00051639054560318],
       [Timestamp('2016-06-22 00:00:00'), 0.0005071830355259743,
        0.00043059308997126926, 0.0004946072684570451],
       [Timestamp('2016-06-23 00:00:00'), 0.00043428318474454176,
        0.0005531033128793341, 0.000415948930235178],
       [Timestamp('2016-06-24 00:00:00'), 0.0005343602862816807,
        0.0006874771857235424, 0.0006170681980190545],
       [Timestamp('2016-06-27 00:00:00'), 0.0005559074735719032,
        0.0005625992079372445, 0.0005891117256986897],
       [Timestamp('2016-06-28 00:00:00'), 0.000481127824134031,
        0.0005628494887160905, 0.0007225528123096994],
       [Timestamp('2016-06-29 00:00:00'), 0.0005237539300612225,
        0.0004976284674405934, 0.0006413364651476455],
       [Timestamp('2016-06-30 00:00:00'), 0.000622096089582509,
        0.00054781945217459, 0.0006857908269169661],
       [Timestamp('2016-07-01 00:00:00'), 0.0006654253520859522,
        0.0006281594414325588, 0.0006959146492845134],
       [Timestamp('2016-07-04 00:00:00'), 0.0010583500675579588,
        0.0008680681569695174, 0.0008427941918898941],
       [Timestamp('2016-07-05 00:00:00'), 0.0007464277807481171,
        0.0006209186290567294, 0.0008020943022077358],
       [Timestamp('2016-07-06 00:00:00'), 0.0008240021334726667,
        0.0007921758817345246, 0.0008741044502375493],
       [Timestamp('2016-07-07 00:00:00'), 0.0006446744296363997,
        0.0005364879262150115, 0.0006910041968619207],
       [Timestamp('2016-07-08 00:00:00'), 0.0006190758952490814,
        0.000529244958825707, 0.0007059208784218829],
       [Timestamp('2016-07-11 00:00:00'), 0.0005196940533779597,
        0.000556565364439892, 0.0006035442430318258],
       [Timestamp('2016-07-12 00:00:00'), 0.0005290897552288798,
        0.0006468145557014837, 0.000855194463233533],
       [Timestamp('2016-07-13 00:00:00'), 0.0006273345037999549,
        0.0010313252771111563, 0.0007968910750065398],
       [Timestamp('2016-07-14 00:00:00'), 0.0005027678307820102,
        0.000641299952053671, 0.0006674599196959719],
       [Timestamp('2016-07-15 00:00:00'), 0.0004204441869447948,
        0.000647493063212554, 0.0006763002123218198],
       [Timestamp('2016-07-18 00:00:00'), 0.00044298266176238395,
        0.0006328196444465846, 0.0006470386149627662],
       [Timestamp('2016-07-19 00:00:00'), 0.0005130223761115057,
        0.0005786198759903877, 0.0007012703811066161],
       [Timestamp('2016-07-20 00:00:00'), 0.0005958054425528036,
        0.0006700263863145537, 0.0006929251566600011],
       [Timestamp('2016-07-21 00:00:00'), 0.0004795227746602912,
        0.0005625899383145057, 0.0005723008280274344],
       [Timestamp('2016-07-22 00:00:00'), 0.0005195511164053755,
        0.0006203641042126634, 0.0006443213078018969],
       [Timestamp('2016-07-25 00:00:00'), 0.0005357508177848598,
        0.0005475284608651237, 0.000579772279674536],
       [Timestamp('2016-07-26 00:00:00'), 0.00041227040428611794,
        0.0004470401388115348, 0.0005761457209791405],
       [Timestamp('2016-07-27 00:00:00'), 0.00044605140008832113,
        0.0005340472751050133, 0.0005877051531162719],
       [Timestamp('2016-07-28 00:00:00'), 0.0005342954451137067,
        0.00041116839307226864, 0.0004927208127544092],
       [Timestamp('2016-07-29 00:00:00'), 0.00045925608457422133,
        0.0005367195914676126, 0.0007397399415247368],
       [Timestamp('2016-08-01 00:00:00'), 0.00045768395862008535,
        0.0004936599313007182, 0.0006282529117506179],
       [Timestamp('2016-08-02 00:00:00'), 0.0005184312096494791,
        0.0005197700309149033, 0.0005069049251378632],
       [Timestamp('2016-08-03 00:00:00'), 0.0005245373017997648,
        0.0005373075967106238, 0.0005054024190750164],
       [Timestamp('2016-08-04 00:00:00'), 0.00046331826217413944,
        0.0006137316817212918, 0.000520484538771337],
       [Timestamp('2016-08-05 00:00:00'), 0.0004954383455536444,
        0.00044279796900134334, 0.000509781326211645],
       [Timestamp('2016-08-08 00:00:00'), 0.00048055027213242884,
        0.00041742446639910516, 0.0004872581355100753],
       [Timestamp('2016-08-09 00:00:00'), 0.0004347638469439805,
        0.0003977999693639188, 0.0004869014674756203],
       [Timestamp('2016-08-10 00:00:00'), 0.00043935614496638776,
        0.0005504358764432117, 0.000540965506624366],
       [Timestamp('2016-08-11 00:00:00'), 0.0004608710863821707,
        0.000342941866562014, 0.0005073631800309126],
       [Timestamp('2016-08-12 00:00:00'), 0.0005760183702383262,
        0.0005013765036799868, 0.0005747030101289224],
       [Timestamp('2016-08-15 00:00:00'), 0.0004512513614777058,
        0.00037702943334583504, 0.0005507332895639108],
       [Timestamp('2016-08-16 00:00:00'), 0.00043257666142745496,
        0.00036587467256818216, 0.00046197896380645163],
       [Timestamp('2016-08-17 00:00:00'), 0.000496664515735338,
        0.0003135741726705445, 0.00044535152872948904],
       [Timestamp('2016-08-18 00:00:00'), 0.0005632071657166244,
        0.00031164082837462233, 0.00044137518709606643],
       [Timestamp('2016-08-19 00:00:00'), 0.000571281945458825,
        0.000324073415226573, 0.0003838449857260132],
       [Timestamp('2016-08-22 00:00:00'), 0.000514376857487631,
        0.0003305145251778264, 0.00046360658707500485],
       [Timestamp('2016-08-23 00:00:00'), 0.00039560353649841044,
        0.0003388282758189926, 0.0004325754833335915],
       [Timestamp('2016-08-24 00:00:00'), 0.0004164806848571013,
        0.00039869185130321933, 0.0004056391641585535],
       [Timestamp('2016-08-25 00:00:00'), 0.00046349601933898775,
        0.00034387353309805, 0.0005061828082577698],
       [Timestamp('2016-08-26 00:00:00'), 0.00046044726889550786,
        0.0004099262003661143, 0.00069493983299185],
       [Timestamp('2016-08-29 00:00:00'), 0.0004491877047420038,
        0.00028903040864520916, 0.00046284225216467763],
       [Timestamp('2016-08-30 00:00:00'), 0.00032452962261739915,
        0.00030020081302325677, 0.0004402159154963495],
       [Timestamp('2016-08-31 00:00:00'), 0.00037257451472411785,
        0.00030139506883792975, 0.0005300840559717576],
       [Timestamp('2016-09-01 00:00:00'), 0.0004713505472422002,
        0.0003256687165355504, 0.00048579156203658357],
       [Timestamp('2016-09-02 00:00:00'), 0.0006686088619696603,
        0.00031415806477442913, 0.0004767212470053228],
       [Timestamp('2016-09-05 00:00:00'), 0.0006284658071955844,
        0.0003248162517320495, 0.0005233689896259205],
       [Timestamp('2016-09-06 00:00:00'), 0.000500951638068725,
        0.0002842255528489639, 0.0004477066695372228],
       [Timestamp('2016-09-07 00:00:00'), 0.00045164323002464506,
        0.0003450439437119059, 0.0005444619152031347],
       [Timestamp('2016-09-08 00:00:00'), 0.0005373552065859251,
        0.00030749159282254584, 0.0004968706540557515],
       [Timestamp('2016-09-09 00:00:00'), 0.0003934578311998167,
        0.00028501905641055685, 0.00045659690358892713],
       [Timestamp('2016-09-12 00:00:00'), 0.0005304915660183161,
        0.0004096806824582275, 0.0006098631114519135],
       [Timestamp('2016-09-13 00:00:00'), 0.00040500417277982933,
        0.000324165986031016, 0.0005087645002013036],
       [Timestamp('2016-09-14 00:00:00'), 0.0005214593447336372,
        0.00028677202228720574, 0.0005030506807000142],
       [Timestamp('2016-09-19 00:00:00'), 0.00049512264948452,
        0.00036723659926479795, 0.0005998846690117644],
       [Timestamp('2016-09-20 00:00:00'), 0.0004801359755338451,
        0.0002669568455491966, 0.0005049125319175838],
       [Timestamp('2016-09-21 00:00:00'), 0.0004901631455590383,
        0.0002862737782923031, 0.0005111673451588669],
       [Timestamp('2016-09-22 00:00:00'), 0.0004893981965318,
        0.00036847868589311487, 0.0005760743444199785],
       [Timestamp('2016-09-23 00:00:00'), 0.00045413989454686984,
        0.0002714105067817556, 0.0004946548151718528],
       [Timestamp('2016-09-26 00:00:00'), 0.0005115623896841486,
        0.000302049067021206, 0.0006082630293400321],
       [Timestamp('2016-09-27 00:00:00'), 0.0004964630969133667,
        0.000404317795147881, 0.0005252063526782465],
       [Timestamp('2016-09-28 00:00:00'), 0.00040000800548036213,
        0.00031492211605119684, 0.0005001565563112964],
       [Timestamp('2016-09-29 00:00:00'), 0.0009551749299242623,
        0.0003953711579804286, 0.0005143672617737191],
       [Timestamp('2016-09-30 00:00:00'), 0.00047180945670230115,
        0.0003055975677654026, 0.00041017102916208006],
       [Timestamp('2016-10-10 00:00:00'), 0.0005720021088230644,
        0.00037049401192489474, 0.0006816471669693215],
       [Timestamp('2016-10-11 00:00:00'), 0.0004951453799206867,
        0.0003710935888607516, 0.0005794926256547587],
       [Timestamp('2016-10-12 00:00:00'), 0.0005263368018963134,
        0.0003830639501503159, 0.0005558712539607329],
       [Timestamp('2016-10-13 00:00:00'), 0.0005044113270118951,
        0.000629092915873652, 0.0005671378319359504],
       [Timestamp('2016-10-14 00:00:00'), 0.0005117083379396438,
        0.00038530306146361933, 0.00061939838226291],
       [Timestamp('2016-10-17 00:00:00'), 0.0005643807471575588,
        0.00029141256527820376, 0.0006443619139186275],
       [Timestamp('2016-10-18 00:00:00'), 0.00046528305415596247,
        0.00026561800194288115, 0.0005227470482207101],
       [Timestamp('2016-10-19 00:00:00'), 0.0005177148586856252,
        0.0003839740678259437, 0.0005278072706485046],
       [Timestamp('2016-10-20 00:00:00'), 0.0004611086800182034,
        0.0003220791190612921, 0.0005122410611197865],
       [Timestamp('2016-10-21 00:00:00'), 0.00046822486636520776,
        0.0003127448819186256, 0.0005352561313942803],
       [Timestamp('2016-10-24 00:00:00'), 0.0004986115877646785,
        0.00031314795236386556, 0.000584187248463929],
       [Timestamp('2016-10-25 00:00:00'), 0.001136196925039797,
        0.000566877459094734, 0.0007684697377197838],
       [Timestamp('2016-10-26 00:00:00'), 0.0009160959873868474,
        0.0003660834150778979, 0.0005912460070595834],
       [Timestamp('2016-10-27 00:00:00'), 0.0007235775230236952,
        0.0003990915279588654, 0.0004806644619876079],
       [Timestamp('2016-10-28 00:00:00'), 0.0008473542113272866,
        0.00040732331636319797, 0.0006597087686774792],
       [Timestamp('2016-10-31 00:00:00'), 0.0009832562763515578,
        0.00043114835751570813, 0.0007724458817125348],
       [Timestamp('2016-11-01 00:00:00'), 0.0007814889591591826,
        0.00045916915115580943, 0.0007658220594042197],
       [Timestamp('2016-11-02 00:00:00'), 0.0006803503441714753,
        0.00048121959106633093, 0.0007125191358360133],
       [Timestamp('2016-11-03 00:00:00'), 0.0009346080343407607,
        0.00052993798536615, 0.0006608157728049986],
       [Timestamp('2016-11-04 00:00:00'), 0.0007543451661878849,
        0.0004768199888560893, 0.0008204981546811345],
       [Timestamp('2016-11-07 00:00:00'), 0.0008681462102375919,
        0.000797935664961196, 0.001001579182211634],
       [Timestamp('2016-11-08 00:00:00'), 0.0008598385055589262,
        0.0008273163328061145, 0.0008806864276617554],
       [Timestamp('2016-11-09 00:00:00'), 0.00133830299487452,
        0.0014682970215055512, 0.0014815295961821465],
       [Timestamp('2016-11-10 00:00:00'), 0.0011005671746678904,
        0.001480675014676087, 0.001176278415633836],
       [Timestamp('2016-11-11 00:00:00'), 0.00229518562243583,
        0.0025543525309958148, 0.002035745967555896],
       [Timestamp('2016-11-14 00:00:00'), 0.0013829154114615343,

In [239]:
pd.DataFrame(intra_df_cop_al.groupby(['date']).pctchange.std())

            pctchange
date
2016-03-10   0.000547
2016-03-11   0.000433
2016-03-14   0.000498
2016-03-15   0.000471
2016-03-16   0.000375
2016-03-17   0.000391
2016-03-18   0.000452
2016-03-21   0.000523
2016-03-22   0.000425
2016-03-23   0.000359
2016-03-24   0.000482
2016-03-25   0.000451
2016-03-28   0.000474
2016-03-29   0.000530
2016-03-30   0.000434
2016-03-31   0.000402
2016-04-01   0.000433
2016-04-05   0.000459
2016-04-06   0.000397
2016-04-07   0.000626
2016-04-08   0.000400
2016-04-11   0.000424
2016-04-12   0.000516
2016-04-13   0.000641
2016-04-14   0.000474
2016-04-15   0.000520
2016-04-18   0.000481
2016-04-19   0.000391
2016-04-20   0.000487
2016-04-21   0.001207
...               ...
2017-01-23   0.000747
2017-01-24   0.000784
2017-01-25   0.000709
2017-01-26   0.000631
2017-02-03   0.000787
2017-02-06   0.000625
2017-02-07   0.000483
2017-02-08   0.000594
2017-02-09   0.000477
2017-02-10   0.000579
2017-02-13   0.000676
2017-02-14   0.000892
2017-02-15   0.000785
2017-02-16   0.000870
2017-02-17   0.000743
2017-02-20   0.000673
2017-02-21   0.000619
2017-02-22   0.000571
2017-02-23   0.000614
2017-02-24   0.000800
2017-02-27   0.000807
2017-02-28   0.000585
2017-03-01   0.000713
2017-03-02   0.000545
2017-03-03   0.000665
2017-03-06   0.000700
2017-03-07   0.000502
2017-03-08   0.000724
2017-03-09   0.000683
2017-03-10   0.000387

[245 rows x 1 columns]

In [240]:
interday_df

,update_date,open,high,low,close,volume,high_yes,low_yes,close_yes
0,2016-03-09,11535,11545,11055,11370,296444,NaN,NaN,NaN
1,2016-03-10,11355,11415,11265,11315,168332,11545,11055,11370
2,2016-03-11,11300,11375,11245,11375,145504,11415,11265,11315
3,2016-03-14,11335,11455,11320,11335,141928,11375,11245,11375
4,2016-03-15,11310,11355,11270,11300,125840,11455,11320,11335
5,2016-03-16,11245,11305,11200,11275,110250,11355,11270,11300
6,2016-03-17,11230,11365,11230,11340,94516,11305,11200,11275
7,2016-03-18,11325,11500,11320,11455,158696,11365,11230,11340
8,2016-03-21,11425,11580,11400,11485,154720,11500,11320,11455
9,2016-03-22,11530,11550,11470,11515,94936,11580,11400,11485
10,2016-03-23,11495,11545,11460,11500,95008,11550,11470,11515
11,2016-03-24,11495,11640,11465,11525,241820,11545,11460,11500
12,2016-03-25,11520,11715,11510,11700,174076,11640,11465,11525
13,2016-03-28,11720,11830,11680,11740,164850,11715,11510,11700
14,2016-03-29,11750,11880,11700,11755,183126,11830,11680,11740
15,2016-03-30,11775,11780,11690,11740,107466,11880,11700,11755
16,2016-03-31,11700,11780,11675,11750,88830,11780,11690,11740
17,2016-04-01,11765,11900,11750,11865,104802,11780,11675,11750
18,2016-04-05,11870,11940,11830,11850,83516,11900,11750,11865
19,2016-04-06,11825,11910,11750,11765,149362,11940,11830,11850
20,2016-04-07,11765,11815,11745,11780,121118,11910,11750,11765
21,2016-04-08,11750,11755,11520,11635,162978,11815,11745,11780
22,2016-04-11,11670,11820,11665,11775,143912,11755,11520,11635
23,2016-04-12,11750,11820,11750,11785,87924,11820,11665,11775
24,2016-04-13,11835,12075,11825,11945,274114,11820,11750,11785
25,2016-04-14,12000,12070,11915,11960,168504,12075,11825,11945
26,2016-04-15,11995,12020,11925,11960,131570,12070,11915,11960
27,2016-04-18,11950,12010,11830,11955,140130,12020,11925,11960
28,2016-04-19,12000,12045,11955,12035,126866,12010,11830,11955
29,2016-04-20,12055,12120,12025,12075,149904,12045,11955,12035
...,...,...,...,...,...,...,...,...,...
216,2017-01-23,13435,13890,13380,13690,476428,13455,13325,13335
217,2017-01-24,13720,13820,13660,13725,224188,13890,13380,13690
218,2017-01-25,13825,14140,13820,14050,365258,13820,13660,13725
219,2017-01-26,13965,14015,13630,13835,280242,14140,13820,14050
220,2017-02-03,13880,13880,13640,13760,115482,14015,13630,13835
221,2017-02-06,13740,13925,13520,13630,220494,13880,13640,13760
222,2017-02-07,13625,13735,13525,13600,156072,13925,13520,13630
223,2017-02-08,13655,13815,13610,13775,116576,13735,13525,13600
224,2017-02-09,13750,13925,13750,13810,127990,13815,13610,13775
225,2017-02-10,13855,13930,13690,13835,149256,13925,13750,13810
226,2017-02-13,13870,14140,13850,14035,260788,13930,13690,13835
227,2017-02-14,14045,14435,14010,14415,426604,14140,13850,14035
228,2017-02-15,14390,14500,14205,14345,443094,14435,14010,14415
229,2017-02-16,14300,14580,14220,14365,407896,14500,14205,14345
230,2017-02-17,14275,14415,14030,14065,364188,14580,14220,14365
231,2017-02-20,14065,14195,13920,14145,323658,14415,14030,14065
232,2017-02-21,14130,14375,14130,14225,295984,14195,13920,14145
233,2017-02-22,14230,14305,13925,13955,342076,14375,14130,14225
234,2017-02-23,13980,14100,13805,13840,310220,14305,13925,13955
235,2017-02-24,13920,13940,13505,13715,350992,14100,13805,13840
236,2017-02-27,13780,13910,13710,13755,305876,13940,13505,13715
237,2017-02-28,13875,14030,13745,13770,297368,13910,13710,13755
238,2017-03-01,13800,14250,13780,14180,345876,14030,13745,13770
239,2017-03-02,14220,14295,14080,14145,248184,14250,13780,14180
240,2017-03-03,14130,14180,13850,14165,256302,14295,14080,14145
241,2017-03-06,14220,14255,13830,13830,201920,14180,13850,14165
242,2017-03-07,13805,13920,13765,13850,125948,14255,13830,13830
243,2017-03-08,13835,13960,13760,13805,197562,13920,13765,13850
244,2017-03-09,13870,13890,13655,13675,241154,13960,13760,13805
245,2017-03-10,NaN,NaN,NaN,13675,NaN,13890,13655,13675